dist: trusty
sudo: required
cache: pip
language: python
matrix:
    include:
        - python: 2.7
          env: LATEST="true" NOTEBOOKS="false" DOCTESTS="false"
        - python: 3.5
          env: LATEST="true" NOTEBOOKS="false" DOCTESTS="false"
        - python: 3.6
          env: LATEST="true" NOTEBOOKS="false" DOCTESTS="true"
        - python: 3.6
          env: LATEST="false" NUMPY_VERSION="1.11" TENSORFLOW_VERSION="1.3.0" NOTEBOOKS="true" DOCTESTS="false"
        - python: 3.5
          env: LATEST="true" NOTEBOOKS="true" DOCTESTS="false"
install:
    - sudo apt-get update
    - source .travis/install_travis_env.sh
script:
    - echo "skip";
#    - bash .travis/run_travis_tests.sh
#after_success:
#    - if [[ "${COVERAGE}" == "true" ]]; then coveralls; codecov; else echo "failed"; fi
notifications:
    email:
        recipients:
            - mail@sebastianraschka.com
    on_success: always
    on_failure: always
